# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-FTP-RetrHandle
version:      0.2
version_from: lib/Net/FTP/RetrHandle.pm
installdirs:  site
requires:
    Fcntl:                         0
    IO::Handle:                    0
    Net::FTP:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
